-- SECURITY: USER ACCOUNT
DROP TABLE IF EXISTS test.account;
CREATE TABLE test.account ( ACCOUNT_NAME VARCHAR(255) NOT NULL,
						PASSWORD VARCHAR(255) NOT NULL,
						ID SERIAL,
						ENABLED BOOL DEFAULT true);

